name: CanberraCollective
favicon: null
layout_spectrum: 0.22446939954534173
typography_spectrum: 0.6132018284406513
title: Canberra Collective - Veicolo Fotografia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.877927883528173
  lightness: 0.30132728326134384
  saturation: 0.1793989969883114
  rhythmicContrast: 0.21605278365314007
purpose: []
